package br.com.usp.labis.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum GoEvidenceEnum {
	
	DIRECT_ASSAY("IDA"), 
	EXPERIMENT("EXP"), 
	PHYSICAL_INTERACTION("IPI"),
	MUTANT_PHENOTYPE("IMP"),
	GENETIC_INTERACTION("IGI"),
	EXPRESSION_PATTERN("IEP") ,
	ELECTRONIC_ANNOTATION("IEA"),
	THROUGHPUT_EXPERIMENT("HTP"),
	THROUGHPUT_DIRECT_ASSAY("HDA"),
	THROUGHPUT_MUTANT_PHENOTYPE("HMP"),
	THROUGHPUT_GENETIC_INTERACTION("HGI"),
	THROUGHPUT_EXPRESSION_PATTERN("HEP"),
	SEQUENCE_OR_STRUCTURAL_SIMILARITY("ISS"),
	SEQUENCE_ORTHOLOGY("ISO"),
	SEQUENCE_ALIGNMENT("ISA"),
	SEQUENCE_MODEL("ISM"),
	GENOMIC_CONTEXT("IGC"),
	BIOLOGICAL_ASPECT_OF_ANCESTOR("IBA"),
	BIOLOGICAL_ASPECT_OF_DESCENDANT("IBD"),
	KEY_RESIDUES("IKR"),
	RAPID_DIVERGENCE("IRD"),
	REVIEWED_COMPUTATIONAL_ANALYSIS("RCA"),
	TRACEABLE_AUTHOR("TAS"),
	NON_TRACEABLE_AUTHOR("NAS"),
	INFERRED_BY_CURATOR("IC"),
	NO_BIOLOGICAL_DATA_AVAILABLE("ND");

	private String evidence;

	GoEvidenceEnum(String evidence) {
		this.evidence = evidence;
	}
	
    @JsonValue
	public String getGoEvidence() {
		return evidence;
	}
}
